### ISSUE TITLE
Prefixed preHandler is not being executed

### ISSUE THREAD

**Issue by ianwalter** [ianwalter/fastify-csrf#1]

**Comment by StarpTech** [comment]
Hi, I just had a look at your code.

* You don't need to register another plugin
* You don't need to provide a prefix it's already passed for your plugin when registering

You code can be simplified:
```js
const fastifyPlugin = require('fastify-plugin')
const Tokens = require('csrf')

module.exports = fastifyPlugin(
  function (fastify, options = {}, next) {
    // Create the pillarjs tokens instance that will be used to generate
    // url/cookie-safe tokens.
    const csrfOptions = options.csrf || {}
    const tokens = new Tokens({ secretLength: 48, ...csrfOptions })

    // Create the csrfToken() request method that allows the server to generate a
    // secret token for the client and a verification token stored in the user's
    // session.
    fastify.decorateRequest('csrfToken', function () {
      const secret = tokens.secretSync()
      this.session.csrfToken = tokens.create(secret)
      return secret
    })

    // Register the preHandler that checks whether requests have the correct CSRF
    // token by comparing the secret token in the csrf-token request header and
    // the verification token stored in the user's session.
    fastify.addHook('preHandler', function (request, reply, next) {
	  // check here
      next()
    })

    // Continue after setup has completed.
    next()
  },
  { dependencies: ['fastify-session'] }
)
```
```js
app.register(fastifyCsrf, { prefix: '/api' })
```

**Comment by ianwalter** [comment]
@StarpTech The prefix doesn't work because I'm using `fastify-plugin` (the docs did warn about this) but I want to use `fastify-plugin` because I wanted to make the `csrfToken` request decorator available for **all** requests.

**Comment by lependu** [comment]
Hi there! Take a look at the [language-parser](https://github.com/lependu/fastify-language-parser) plugin, which basically does the same task what you want to achieve. Espesially the [integration test](https://github.com/lependu/fastify-language-parser/blob/c70e46b1e96cbdd2cce9e4dfda61a01789a36c74/test/plugin.test.js#L51-L107) part where you can see, how scoping works with `fastify-plugin` and why you don't need to scope inside your plugin.

**Comment by ianwalter** [comment]
@lependu Yea, I guess what I'm trying to do would be a problem with the csurf middleware in express too. I guess it's not a big deal and I'll just remove the extra scoping workaround.
